### ISSUE TITLE
QCPump v0.3.16 Breaks DQA3 SQL Server connection

### ISSUE THREAD

**Issue by ash-cullen** [qatrackplus/qcpump#12]
At my site, we use DQA3 v3.1.1 with an SQL database hosted on a separate SQL server, and use QCPump to sync to QATrack+ 3.1.1.3. Before the QCPump v0.3.16 upgrade, this functionality was working, however since the upgrade, validation of the DQA3Reader configuration fails.

The logs show the following:
`2023-07-31 14:23:30,982,DQA3: SQL Server,DEBUG,Starting validation for section Test List 60395d89-fe89-4ced-a3cb-4dfadb4c793d
2023-07-31 14:23:30,998,DQA3: SQL Server,DEBUG,Using results from group 60395d89-fe89-4ced-a3cb-4dfadb4c793d for section Pump because they are the most recent
2023-07-31 14:23:30,999,DQA3: SQL Server,CRITICAL,Traceback (most recent call last):
  File "qcpump\pumps\base.py", line 925, in _run_validation_thread
  File "C:\Program Files (x86)\qcpump\contrib\pumps\dqa3\dqa3pump.py", line 132, in validate_dqa3reader
    connect_kwargs = self.db_connect_kwargs()
  File "C:\Program Files (x86)\qcpump\contrib\pumps\dqa3\dqa3pump.py", line 169, in db_connect_kwargs
    'charset': config['charset'],
KeyError: 'charset'

NoneType: None

2023-07-31 14:23:31,000,DQA3: SQL Server,DEBUG,Using results from group 60395d89-fe89-4ced-a3cb-4dfadb4c793d for section DQA3Reader because they are the most recent
2023-07-31 14:23:31,001,DQA3: SQL Server,DEBUG,Validation Error for DQA3Reader: Invalid Validator Implementation`

Reverting dqa3pump.py to v0.3.14 fixes this issue at my site.

**Comment by randlet** [comment]
Argh, you're right I botched that sorry. Will get an update out shortly.

**Comment by ash-cullen** [comment]
No problem Randy, thanks for the speedy update! I can confirm v0.3.17 works fine at my site.
